# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-18 22:15
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190213_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name=b'Icerik'),
        ),
    ]
